# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: MyJob
  pool:
    vmImage: 'EC2AMAZ-HUQ7UFJ' 

  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'dir'
  - task: Npm@1
    inputs:
      command: 'install'
  
