trigger:
- master

pool:
  name: Ec2_Instance

jobs:
- job: DeployToIIS
  displayName: 'Deploy to IIS'
  steps:
  - checkout: self

  # Your build and test steps go here if needed

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        Get-Website | Select-Object -Property Name

  - task: IISWebAppManagementOnMachineGroup@0
    inputs:
      EnableIIS: true
      IISDeploymentType: 'IISWebsite'
      ActionIISWebsite: 'StopWebsite'
      StartStopWebsiteName: 'Dotnet'

  - script: |
      xcopy "$(System.DefaultWorkingDirectory)" "C:\Dotnet" /E /Y
    displayName: 'Deploy to IIS'


  - task: IISWebAppManagementOnMachineGroup@0
    inputs:
      IISDeploymentType: 'IISWebsite'
      ActionIISWebsite: 'StartWebsite'
      StartStopWebsiteName: 'Dotnet'
