# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Ec2_Instance

steps:
- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: 'Dotnet'
    VirtualApplication: 'C:\Dotnet'
    Package: '$(System.DefaultWorkingDirectory)\**\*.zip'